# -*- coding: utf-8 -*-
"""Yolo object detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX8CyJSm2u8ffdpWin292MkprrhTYKQp
"""

!invidia-smi

!pip  install ultralytics

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import  Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="3bTnFgb6WKFlDWOa6Ndy")
project = rf.workspace("container-02hn5").project("dita2")
version = project.version(6)
dataset = version.download("yolov11")

dataset.location
# add2582a5509ac31d9c68d7c659c0f40ad0a6031

!yolo task=detect mode=train data={dataset.location}/data.yaml model="yolo11n.pt" epochs=50 imgsz=640



#f1 score
Image("/content/runs/detect/train4/F1_curve.png", width=500)

# confusion matrix
Image("/content/runs/detect/train4/confusion_matrix.png", width=500)

Image("/content/runs/detect/train4/R_curve.png", width=500)

Image("//content/runs/detect/train4/results.png", width=500)

Image("/content/runs/detect/train4/confusion_matrix_normalized.png", width=500)